// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygefhzowjdwpbznujsax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnZWZoem93amR3cGJ6bnVqc2F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTk5MjUsImV4cCI6MjA2NjE3NTkyNX0.t5Nu119f90DL7djLvKpic9WqoE6Kmd0GkBR0eWslJZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);